name: cs471generals
dependencies:
    - python=3.11.2
    - pip:
        - websocket-client
        - PyAudio==0.2.13
        - SpeechRecognition==3.10.0
        - numpy==1.24.2
        - fuzzywuzzy==0.18.0
